services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    build: .
    pid: "host"
    env_file:
      - .env
    command: gunicorn djangoweb.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - media_volume:/app/media
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
    expose:
      - "8000"

  tunnel:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=eyJhIjoiYzU1MTU3YzMyMDMzNWY2ODIzZmJiNWQ0Yzg0YmM1ZTkiLCJ0IjoiNTBjNDZmMzMtMDg1MC00OGNhLThjMDktYjJkM2NhZTdiNzQwIiwicyI6Ik4ySXpZamxtWkRRdFpUazVOaTAwWXpZeExXRmlaamN0TldSbU1XUXlNMk5sTW1JNCJ9  # Paste your token here
    depends_on:
      - web

volumes:
  postgres_data:
