# Generated by Django 6.0.3 on 2026-03-14 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('image', models.ImageField(upload_to='projects/')),
                ('link', models.URLField(help_text='Link to the  project (e.g., GitHub, live demo)')),
                ('order', models.IntegerField(default=0, help_text='Used to sort the gallery')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
